### ISSUE TITLE
Change Tags to be case insensitive

### ISSUE THREAD

**Issue by chan-j-d** [AY2021S1-CS2103T-W10-4/tp#122]
Since we are enabling search by `Tag`s, our group has decided that a `Tag` like `cs2103` should be the same as `CS2103`. As such, we should default our `Tag`s either capitalize or lower-case all letters in `Tag`s.

**Comment by fyshhh** [comment]
i think we can give the user the option to capitalise their `Tag`s and use regex to ignore case sensitivity in our searches.

**Comment by chan-j-d** [comment]
I don't really agree with this. I believe that we should limit the options the user has in this case. Otherwise, suppose a user creates a tag `Cs2103` and starts assigning things to it. This tag will be permanently stuck at `Cs2103` and unless we give them a new command to change the specification of the tag name to either `CS2103` or `cs2103`. 

Not to say that forcing upper-case is definitely a better solution than what you suggested, but I do feel that enforcing capitalization is a more agreeable policy as opposed to someone not realizing that they can't change the capitalization of their tags after adding hundreds of contacts under the tag.

**Comment by fyshhh** [comment]
i see your point, but i think the best solution is just to include a way for them to edit their tags after they've been created. as a user, i would not like having to be forced into using a certain case (be it upper or lower), as different cases can add nuance to the tags.

**Comment by chan-j-d** [comment]
Upon further deliberation, I realize that an edit tag name-type command is inevitable. As such, this should cover whatever I was concerned with initially. Thanks for the suggestion!

**Comment by chan-j-d** [comment]
On further further deliberation, I realize there is still a necessity to standardize the capitalization of tags. When two separate Persons are added with tags `cs2103` and `CS2103`, should a lookup of the tag produce both? Otherwise, if yes then why not standardise how the tags themselves look. If no, then I personally feel that it kind of beats the point of implementing search by tags to begin with.
