### ISSUE TITLE
Maintain the CI passing status

### ISSUE THREAD

**Issue by damithc** [AY2021S1-CS2103T-W10-4/tp#63]
Looks like your CI is failing for the past couple of commits. CI should be kept passing at all times or else it defeats the purpose of having CI. Consider 'protecting' your master branch to prevent any PR that fails CI from merging.

**Comment by chan-j-d** [comment]
Issue has been fixed! Thanks for the notification. I ticked the 'Require status checks to pass before merging' option without realizing that I had to specify which CIs I wanted passed before being able to merge. This has been addressed and our CI is now passing.
